version: "3"
services:
  player-service:
    image: voigtsebastian/gladiator-player-service:debug
    depends_on:
      - player-pg-db
    ports:
      - "8080:8080"
    environment:
      - DOCKERENV=TRUE
      - DATABASE_URL=postgresql://postgres:unsecure_password@localhost/gladiators_player_service
  player-pg-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gladiators_player_service
      - POSTGRES_PASSWORD=unsecure_password
