addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.11.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.2")
resolvers += Resolver.bintrayRepo("givers", "maven")
addSbtPlugin("givers.vuefy" % "sbt-vuefy" % "5.0.0")
// addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
// addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.12")
